SELECT CUSTOMER.*, CUSTOMER_ADDRESS.*, CUSTOMER_EMAIL.*, CUSTOMER_PHONE.*
FROM CUSTOMER CUSTOMER, CUSTOMER_ADDRESS CUSTOMER_ADDRESS, CUSTOMER_EMAIL CUSTOMER_EMAIL, CUSTOMER_PHONE CUSTOMER_PHONE
WHERE
    CUSTOMER_ADDRESS.customer_ID = CUSTOMER.customer_ID
    AND CUSTOMER_EMAIL.customer_ID = CUSTOMER.customer_ID
    AND CUSTOMER_PHONE.customer_ID = CUSTOMER.customer_ID;
